// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtQtwpUHKMs_M82LjhejvV8VqMMBUCC0s',
    appId: '1:145050408657:web:f62a25873ae63c12f097f0',
    messagingSenderId: '145050408657',
    projectId: 'emergensy-ca0f3',
    authDomain: 'emergensy-ca0f3.firebaseapp.com',
    storageBucket: 'emergensy-ca0f3.firebasestorage.app',
    measurementId: 'G-NNHXDT46SW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu6Tz_YTNeKugjbqN9l4AWfV6_zSo1bEU',
    appId: '1:145050408657:android:9bdbb8e2f09c3531f097f0',
    messagingSenderId: '145050408657',
    projectId: 'emergensy-ca0f3',
    storageBucket: 'emergensy-ca0f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAnCE1LejJ3hR2TIBJJDcLzXAz0Hzy9uY',
    appId: '1:145050408657:ios:58f4f2758b59678af097f0',
    messagingSenderId: '145050408657',
    projectId: 'emergensy-ca0f3',
    storageBucket: 'emergensy-ca0f3.firebasestorage.app',
    iosBundleId: 'com.example.emergensy',
  );
}
